# Generated by Django 5.1.4 on 2025-05-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('partner_name', models.CharField(blank=True, max_length=100)),
                ('categories', models.CharField(max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
