# Generated by Django 5.1.4 on 2025-05-25 15:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentregistration',
            name='categories',
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='category',
            field=models.CharField(choices=[('singles', 'Singles'), ('beginner_doubles', 'Beginner Doubles'), ('intermediate_mens_doubles', 'Intermediate Mens Doubles'), ('intermediate_+_mens_doubles', 'Intermediate+ Mens Doubles'), ('womens_doubles', 'Womens Doubles'), ('mixed_doubles', 'Mixed Doubles'), ('triplets', 'Triplets')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
