# Generated by Django 5.1.4 on 2025-05-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_tournamentregistration_registered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='partner_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='partner_phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='player_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
