# Generated by Django 5.1.4 on 2025-05-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_tournamentregistration_partner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='partner_2_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='partner_2_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
