# Generated by Django 5.1.4 on 2025-05-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_tournamentregistration_partner_2_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentregistration',
            name='partner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
