# Generated by Django 5.1.4 on 2025-05-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_alter_tournamentregistration_partner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentregistration',
            name='partner_2_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='partner_2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='partner_2_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='partner_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='partner_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='player_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
